# Documentation: https://rmk.rs/docs/configuration.html
[keyboard]
name = "Sweek"
product_name = "Sweek Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "rp2040"

[rmk]
# Mouse key interval (ms) - controls mouse movement speed
mouse_key_interval = 5

[storage]
# Clear all storage data on boot, including keymap, BLE bonds, etc
# clear_storage = true

[host]
# Enable or disable Vial support (default: true)
vial_enabled = true
# Unlock keys for Vial security (optional)
# Keys must be pressed simultaneously to unlock Vial configuration
unlock_keys = [[0, 0], [2, 0]]  # Keys at (row=0,col=0) and (row=0,col=1)

[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true
# col2row = true
rows = 4
cols = 10
layers = 7
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8) (0,9)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8) (1,9)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8) (2,9)
            (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) 
"""

[aliases]
EXLM = "WM(Kc1, LShift)"
AT = "WM(Kc2, LShift)"
HASH = "WM(Kc3, LShift)"
DLR = "WM(Kc4, LShift)"
PERC = "WM(Kc5, LShift)"
CIRC = "WM(Kc6, LShift)"
AMPR = "WM(Kc7, LShift)"
ASTR = "WM(Kc8, LShift)"
LPRN = "WM(Kc9, LShift)"
RPRN = "WM(Kc0, LShift)"
UNDS = "WM(Minus, LShift)"
PLUS = "WM(Equal, LShift)"
LCBR = "WM(LeftBracket, LShift)"
RCBR = "WM(RightBracket, LShift)"
COLN = "WM(Semicolon, LShift)"
DQUO = "WM(Quote, LShift)"
PIPE = "WM(Backslash, LShift)"
TILD = "WM(Grave, LShift)"

ALT_F4 = "WM(F4, LAlt)"
CTL_ALT = "WM(LAlt, LCtrl)"
CTLALTD = "WM(Del, LCtrl | LAlt)"
CTLSFTT = "WM(T, LCtrl | LShift)"
LSFTDEL = "WM(Del, LShift)"

NXT_WIN = "WM(Tab, LAlt)"
PRV_WIN = "WM(Tab, LAlt | LShift)"

R_L1 = "LT(1, R, HRM)"
S_L2 = "LT(2, S, HRM)"
T_L3 = "LT(3, T, HRM)"
E_L4 = "LT(4, E, HRM)"
ENT_L5 = "LT(5, ent, FH)"
ESC_L5 = "LT(5, esc, FH)"
N_L6 = "LT(6, N, HRM)"

DOT_APP = "TH(Dot, Menu, FH)"
BSPC_ALT = "MT(bspc, RAlt, FH)"
SPC_ALT = "MT(spc, LAlt, FH)"

[[layer]]
name = "base"
keys = """
Q     W      F      P      G           J      L      O      Y        scln
A     @R_L1  @S_L2  @T_L3  D           H      @N_L6  @E_L4  I        U
Z     X      C      V      B           K      M      Comma  @DOT_APP slsh
        LCtrl  @SPC_ALT  @ESC_L5       @ENT_L5  @BSPC_ALT   OSM(LShift)
"""
encoders = [["Up", "Down"], ["Right", "Left"]]

[[layer]]
name = "mouse"
keys = """
_ _ _          _  _                _  MouseBtn1  ms_whlu  MouseBtn2 _
_ _ MouseBtn1  _  MouseBtn2        _  ms_left    ms_down  ms_up     ms_right
_ _ _          _  _                _  MouseBtn3  ms_whld  _         _
               _ _ _               _ _ _   
"""
encoders = [["Right","Left"], ["Tab","WM(Tab, LShift)"]]

[[layer]]
name = "number"
keys = """
_ Up    _  _     _                 KpPlus   Kc7  Kc8  kc9  KpAsterisk
_ Left  _  Right _                 KpMinus  Kc4  Kc5  Kc6  KpDot
_ Down  _  Comma _                 Kc0      Kc1  Kc2  Kc3  KpSlash
        _ _ _                      _ _ _
"""
encoders = [["_","_"], ["WM(ms_whlu, LCtrl)","WM(ms_whld, LCtrl)"]]

[[layer]]
name = "function"
keys = """
_       @PRV_WIN @NXT_WIN _ _                        _    F7     F8     F9   F10
@ALT_F4 @CTLSFTT @LSFTDEL _ _                        _    F4     F5     F6   F11
_       @CTL_ALT @CTLALTD _ _                        _    F1     F2     F3   F12
                        _ _ _                        _ _ _
"""
encoders = [["_", "_"], ["AudioVolUp", "AudioVolDown"]]

[[layer]]
name = "symbols"
keys = """
@EXLM @AT   @HASH        @DLR  @PERC                @CIRC    @AMPR     _     Grave  _
Minus Equal LeftBracket  Quote Backslash            @ASTR    @LPRN     _     @RPRN  _
@PLUS @UNDS RightBracket @RCBR @PIPE                _        nubs      _     _      _
                         _ _ _                      RCtrl _ _
"""
encoders = [["WM(Right, LShift)","WM(Left, LShift)"], ["_","_"]]

[[layer]]
name = "nav"
keys = """
caps Home pgup Del   LShift      _     _    pgup  Home  _
Left Down Up   Right OSM(LGui)   TG(1) bspc _     _     _
_    End  pgdn bspc  ent         Menu  _    pgdn  End   _
                     _ _ _       _ _ _
"""
encoders = [["_","_"], ["_","_"]]

[[layer]]
name = "Kron"
keys = """
WM(Kc1, LGui) WM(Kc2, LGui) WM(Kc3, LGui)   WM(Kc4, LGui) WM(Kc5, LGui)          _  _  _  _  _
WM(H, LGui)   WM(J, LGui)   WM(K, LGui)     WM(L, LGui)   WM(ent, LGui)          _  _  _  _  _
WM(Q, LGui)   WM(M, LGui)   WM(Comma, LGui) WM(Dot, LGui) WM(spc, LGui)          _  _  _  _  _
                            LGui            LCtrl         LShift                 _ _ _
"""
encoders = [["_","_"], ["_","_"]]


[behavior]
# tap_hold = { enable_hrm = true }

[behavior.combo]
timeout = "50ms"
combos = [
  # Press J and K keys simultaneously to output Escape key
  { actions = ["W", "F"], output = "Tab" },
  { actions = ["F", "P"], output = "CapsWordToggle"},
  { actions = ["O", "Y"], output = "Del" },
  { actions = ["O", "L"], output = "LeftBracket" },
]

[behavior.morse.profiles]
# This profile is recommended on the home row, when enable_flow_tap = true, and the hold action activates a layer or acts as a modifier (aka home row mod)
HRM = { unilateral_tap = true, permissive_hold = true, hold_timeout = "250ms", gap_timeout = "250ms" }
# This profile is recommended when the hold action activates a layer or acts as a modifier (without HRM) (for example thumb keys)
FH = { hold_on_other_press = true, unilateral_tap = false, hold_timeout = "200ms", gap_timeout = "200ms" }

[split]
connection = "serial"

[split.central] #Left
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
[split.central.matrix]
row_pins = ["PIN_29", "PIN_28", "PIN_27", "PIN_26"]
col_pins = ["PIN_3", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]

[[split.central.input_device.encoder]]
pin_a = "PIN_10"
pin_b = "PIN_9"
internal_pullup = true
phase = "resolution"
resolution = { detent = 20, pulse = 12 }
reverse = false

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
[split.peripheral.matrix]
row_pins = ["PIN_3", "PIN_4", "PIN_5", "PIN_6"]
col_pins = ["PIN_15", "PIN_26", "PIN_27", "PIN_28", "PIN_29"]

[[split.peripheral.input_device.encoder]]
pin_a = "PIN_9"
pin_b = "PIN_10"
internal_pullup = true
phase = "resolution"
resolution = { detent = 20, pulse = 12 }
reverse = false
